#write -I $(INCDIR)

INCDEP      := -I $(HEADERDIR)\
	    -I $(SRCDIR)/LCD\
	    -I $(SRCDIR)/UART\
	    -I $(SRCDIR)/RING\
	    -I $(SRCDIR)/BLUETOOTH\
	    -I $(SRCDIR)/rtos\
	    -I $(SRCDIR)/
